services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./conf:/verdaccio/conf"
      - "verdaccio-volume:/verdaccio/storage" # Mount volume for persistent data
networks:
  node-network:
    driver: bridge
volumes:
  verdaccio-volume:
    driver: local
